== kafka-metrics

image:https://travis-ci.org/functionalops/kafka-metrics.svg?branch=master["Build Status", link="https://travis-ci.org/functionalops/kafka-metrics"]

A JMX client for Kafka metrics.

=== Status

This is a work in progress. There is a lot left to do such as:

* add JMX notification listener support
* add scalaz-stream integration

=== Prerequisites

1. Java 7 or 8
2. Scala 2.11.4
3. SBT 0.13.0+

=== License

This is released under the BSD 3-clause license. See link:LICENSE for details.

=== Getting Started

Inside the root directory of the repository:

1. Launch SBT:

        $ sbt

2. Compile everything and run all tests:

        > test

3. Try a basic example:

        scala> import functionalops.kafka.metrics._
        import functionalops.kafka.metrics._
        scala> JMXRunnerMain.main(Array.empty[String])
        Domains: JMImplementation|com.sun.management|java.nio|"kafka.cluster"|ServiceStatus|"kafka.consumer"|"kafka.log"|kafka|"kafka.server"|kafka.controller|java.lang|"kafka.network"|"kafka.controller"|java.util.logging
        MBean count: 5976

Make sure you change `kafka-test` hostname and `9093` port to the appropriate
values

=== Code Structure

I use a less common structure to my code than many Scala projects so here is
the code structure outline and explanation:

* *Types:* I use a _more_ functional style of coding in Scala and as a
  result start coding from _closed_ algebraic data types (usually sum,
  product, and recursive types), which define the basic elements of the
  domain. These traits (types) and corresponding case classes/objects (value
  constructors) can be found in the `Types` trait for namespacing. See below
  for description of namespace organization.
* *"Classes":*  this does not refer to OO classes but rather typeclass
  definitions. I have a trait named `Classes` which contains typeclass
  definitions used to extend our basic sum, product, and recursive data
  types.
* *"Instances":* again this does not refer to "instances" of OO classes,
  rather this refers to implementations of typeclasses for specific types.
  In the trait named `Instances` you will find a number of implicits that
  can be mixed in to different contexts later the allows Scala to find
  the correct instance definition for a specific type of a typeclass based
  on the scope it is introduced. More specific scopes have higher precedence
  which means the default `kafka-metrics` package instance definitions can be
  overridden in applicaation/client code at a higher level if necessary.
* *Functions:* I have a trait named `Functions`, which along side the
  interface to our core types and typeclasses provides the public API for
  the `kafka-metrics` library/toolkit.
* *Namespacing:* You will note I am using traits for namespacing primitives
  that I then use to mixin to objects used for external package namespacing.
